removed public subnets
sourcefuse/arc-lza-config pull request #5
Opened 2023-08-24 14:48 UTC by AsysGuptaSF

Removed public subnets and NAT gateways from production VPC.

2023-08-25 12:21 UTC, jamescrowley321 requested changes

2023-08-25 12:21 UTC, jamescrowley321 commented on hipaa/network-config.yaml
> +      # - name: HIS-WL-Prod-Public-App-A
Remove commented out code.

2023-08-25 12:21 UTC, jamescrowley321 commented on hipaa/network-config.yaml
> +      # - name: HIS-WL-Prod-Public-App-A
Remove commented out code.

2023-08-25 12:21 UTC, jamescrowley321 commented on hipaa/network-config.yaml
> +    # natGateways:
Remove commented out code.

2023-08-28 03:11 UTC, AsysGuptaSF commented on hipaa/network-config.yaml
> +      # - name: HIS-WL-Prod-Public-App-A
Done.

2023-08-28 03:12 UTC, AsysGuptaSF commented on hipaa/network-config.yaml
> +      # - name: HIS-WL-Prod-Public-App-A
Done.

2023-08-28 03:12 UTC, AsysGuptaSF commented on hipaa/network-config.yaml
> +    # natGateways:
Removed commented out code.

2023-08-29 13:11 UTC, merged